[package]
name = "tictactoe"
version = "0.2.0"
authors = ["Pedro Fedricci <pedromfedricci@gmail.com>"]

edition = "2021"
# edition 2021 implies resolver = "2"
# resolver = "2"

# stabilized bindings_after_at
rust-version = "1.56"

[dependencies]
